-- bolivia: product/article master
-- source: vw_artigoz
-- returns: product hierarchy and attributes

select
    a.idartigo,
    a.idsector,
    a.sector,
    a.idproduto,
    a.produto,
    a.idsub,
    a.sub,
    a.idconteudo,
    a.conteudo,
    a.mwp_ready,
    a.mwp_idpl,
    a.mwp_pl,
    a.mwp_idcompany,
    a.mwp_company,
    a.mwp_idbrand,
    a.mwp_brand,
    a.mwp_idvariety,
    a.mwp_variety,
    a.mwp_idav,
    a.mwp_addedvalue,
    a.idfabricante,
    a.fabricante,
    a.idmarca,
    a.marca,
    a.cdc01,
    a.clas01,
    a.cdc02,
    a.clas02,
    a.cdc03,
    a.clas03,
    a.cdc04,
    a.clas04,
    a.cdc05,
    a.clas05,
    a.flggranel,
    a.granel,
    a.coef1,
    a.unicoef1,
    a.coef2,
    a.unicoef2,
    a.coef3,
    a.unicoef3,
    a.flgativo,
    a.codbar,
    a.codbar2,
    a.codbar3,
    a.flgpack,
    a.unidadespack,
    a.idartigoind,
    a.dtcriacao,
    a.fonteinfo,
    a.nroactos,
    a.lastmonth,
    a.avgprice,
    a.considerar,
    a.considerarooh,
    p.flgdesativacao,
    p.idcategoria
from {schema}.vw_artigoz a
left join {schema}.a_produto p
    on a.idproduto = p.idproduto
