-- cam: rg_panelis
-- columns: 49
-- Note: autos, edpsh, ni, origen_dom, seqdom do not exist in CAM

select
    iddomicilio,
    ano,
    pais,
    npan,
    edac,
    slac,
    nse_loc,
    ni12,
    adol,
    ime,
    ciudad,
    cv,
    edbeq1,
    edbeq2,
    edbeq3,
    edbeq4,
    shopseg,
    nsereg,
    nime18,
    edjf,
    paiscam,
    region,
    edacnew,
    mirror01,
    mirror02,
    mirror03,
    mirror04,
    mirror05,
    mirror06,
    mirror07,
    mirror08,
    mirror09,
    mirror10,
    mirror11,
    mirror12,
    ni_inds,
    caricam01,
    caricam02,
    caricam03,
    caricam04,
    caricam05,
    caricam06,
    caricam07,
    caricam08,
    caricam09,
    caricam10,
    caricam11,
    caricam12,
    ksl01
from rg_panelis
where ano >= {start_year} and ano <= {end_year}
